### ISSUE TITLE
Research + Test `KubernetesPodOperator`

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/astronomer-ee#116] opened 2018-08-09 22:03 UTC
Currently a request from 2 customers.

For those two cases, we're thinking the `KubernetesPodOperator` might actually be a better alternative to a Docker operator for a shared setting (instead of having containers running on the cluster). It should be a relatively seamless transition into our environment.

- We’ve also talked about the fact that we don’t expose the DockerSocket for security purposes - but we shouldn’t run into that issue with the Kubes Pod.

Leaving this to @vparekh94 + @schnie, but given that it's a customer ask I'd love to get something here by early to mid next week.

Let me know how I can support! Since our customers are taking a look at this alongside us, any additional documentation on the operator that you guys are looking at would be helpful.

**Comment by schnie** [comment] 2018-08-10 05:30
I don't think it's meant for Composer. It was created at Bloomberg before Composer was released. I'll look at this soon and get back to you!

**Comment by paolaperaza** [comment] 2018-08-10 13:46
Oh oh, interesting. Noted! Took that from a note Viraj, Josh and I sent to a customer, haha

**Comment by schnie** [comment] 2018-08-13 12:55
Hey @paolaperaza gonna look into this today. Who is interested in this? Are they looking at EE or cloud?

**Comment by vparekh94** [comment] 2018-08-13 13:10
@schnie there's one looking at it for cloud and one for EE.

I was trying to rig something together based on this last week:
https://cloud.google.com/composer/docs/how-to/using/using-kubernetes-pod-operator?authuser=0&hl=ru

but I kept running into issues on fetching the config issue

**Comment by schnie** [comment] 2018-08-13 13:30
We'll also need a 1.10 image for this.

**Comment by schnie** [comment] 2018-08-13 15:27
Oh ok. Well I'm working on refactoring astronomer repo now so we can have
multiple official versions anyway. So the problem is missing section in
airflow.cfg, which we can add to the official 1.10 image. Check the
airflow.cfg in master now and pull the default kube sections into yours and
try again.

**Comment by schnie** [comment] 2018-08-14 02:46
@vparekh94 did you get a chance to test with an updated `airflow.cfg`?

**Comment by vparekh94** [comment] 2018-08-14 11:58
Did not last night. On my todo list for today.

**Comment by schnie** [comment] 2018-08-21 01:06
@paolaperaza @vparekh94 is this for a cloud or EE customer?

**Comment by vparekh94** [comment] 2018-08-21 21:28
Wrote a guide on how to do this in EE - will wait to close this out until we can support it in cloud:
https://www.astronomer.io/guides/kubepod-operator/

**Comment by schnie** [comment] 2018-09-10 20:26
This should be good to go with the v0.5.0 release: https://github.com/astronomerio/helm.astronomer.io/blob/master/CHANGELOG.md

Closing this out now. We'll be upgrading cloud over the next few days.

**Closed by schnie** 2018-09-10 20:26 UTC
Labels: 1: Support/Bug, 5: Improvement
